export default {
  LANGS: 'Languages',
  HOME: 'Home',
  SPORTS: 'Sportsbook',
  LIVE_CASINO: 'Live Casino',
  SLOTS: 'Slot',
  LOTTERY: 'Lottery',
  PROMOTIONS: 'Promotions',
  CONTACT_US: 'Contact Us',
  LIVE_CHAT: 'Live Chat',
  WECHAT: 'Wechat',
  BANKING: 'Banking',
  ABOUT_US: 'ABOUT US',
  RESPONSIBLE_GAMING: 'RESPONSIBLE GAMING',
  TERMS_OF_USE: 'TERMS OF USE',
  TRUSTED_PAYMENT: 'Trusted Payment',
  TRANSFER: 'Transfer',
  TOPUP: 'Topup',
  WITHDRAW: 'Withdraw',
  ACCOUNT: 'Account',
  HISTORIES: 'Histories',
  REPORTS: 'Reports',
  DOWNLOAD: 'Download',
  LOGOUT: 'Logout',
  EDIT_PROFILE: 'Edit Profile',
  CHANGE_PASSWORD: 'Change Password',

  // FORM AREA
  BANK_NAME: 'Please Enter Bank Name (full)',
  BANK_ACCOUNT_NAME: 'Please Enter Bank Account Name',
  BANK_ACCOUNT_NO: 'Please Enter Bank Account No',
  WITHDRAW_AMOUNT: 'Please Enter Withdraw Amount',
  WITHDRAW_NOW: 'WITHDRAW NOW',
  SELECT_BANK: 'Select bank',
  TOPUP_AMOUNT: 'Please enter amount',
  AGREEMENT: 'I agree to terms and conditions',
  ONLINE_TOP_UP_NOW: 'ONLINE TOP UP NOW',
  DEPOSIT_WITH_RECEIPT: 'DEPOSIT WITH RECEIPT',
  DEPOSIT_AMOUNT: 'Please Enter Deposit Amount',
  DEPSOSIT_BONUS: 'Claim deposit bonus',
  TRANSFER_IN: 'Transfer In',
  TRANSFER_OUT: 'Transfer Out',
  TYPE_TRANS: 'Select Type Transaction',
  SUBMIT: 'SUBMIT NOW',

  LOADING: 'loading',
  FROM: 'From Date',
  TO: 'To Date',
  TRANS_SUC: 'Transfer Successful',
  TRANS_ERR: 'Transfer Error',
  TRANS_DONE: 'Transfer is successfully finished',
  GOT_IT: 'Got it',
  SELECT_GAME: 'Select Game',
  CLAIM_LOYALTY_BONUS: 'Claim loyalty bonus',
  DEPO_SUC: 'Deposit Successful',
  DEPO_ERR: 'Deposit Error',
  DEPO_DONE: 'Your request submitted successfully',
  DEPOSIT: 'Deposit',
  FILE: 'file',
  WITH_SUC: 'Withdraw Successful',
  WITH_ERR: 'Withdraw Error',
  WITH_DONE: 'Your request submitted successfully',
  CLICK_DOWNLOAD: 'Click to Download',
  ENTER_MOBILE: 'Enter Mobile No',
  ENTER_PASS: 'Enter Password',
  SIGN_IN: 'Sign in',
  REGISTER: 'Register',
  ENTER_DISPLAY_NAME: 'Enter Your Display Name',
  ENTER_EMAIL: 'Enter Your Primary Email',
  ENTER_AGENT: 'Enter affiliate code',
  RETYPE_PASS: 'Retype Your Password',
  BACK_TO_LOGIN: 'BACK TO LOGIN'
}