export default {
  LANGS: 'Bahasa',
  HOME: 'HOME',
  SPORTS: 'Bola',
  LIVE_CASINO: 'Kasino',
  SLOT: 'Slot',
  LOTTERY: 'Togel',
  PROMOTIONS: 'Promosi',
  CONTACT_US: 'Hubungi Kami',
  LIVE_CHAT: 'Live Chat',
  WECHAT: 'WeChat',
  BANKING: 'Perbankan',
  ABOUT_US: 'TENTANG KAMI',
  RESPONSIBLE_GAMING: 'GAMING YANG BERTANGGUNG JAWAB',
  TERMS_OF_USE: 'PERSYARATAN PENGGUNAAN',
  TRUSTED_PAYMENT: 'Pembayaran Tepercaya',
  TRANSFER: 'pindah',
  TOPUP: 'isi ulang',
  WITHDRAW: 'Mundur',
  ACCOUNT: 'Akun',
  HISTORIES: 'Histories',
  REPORTS: 'Reports',
  DOWNLOAD: 'Unduh',
  LOGOUT: 'Keluar',
  EDIT_PROFILE: 'edisi Profil',
  CHANGE_PASSWORD: 'Ubah Kata Sandi',

  // BENTUK AREA
  BANK_NAME: 'Silakan Masukkan Nama Bank (lengkap)',
  BANK_ACCOUNT_NAME: 'Silakan Masukkan Nama Rekening Bank',
  BANK_ACCOUNT_NO: 'Silakan Masukkan Nomor Rekening Bank',
  WITHDRAW_AMOUNT: 'Silakan Masukkan Jumlah Penarikan',
  WITHDRAW_NOW: 'MENARIK SEKARANG',
  SELECT_BANK: 'Pilih bank',
  TOPUP_AMOUNT: 'Silakan Masukkan jumlah',
  AGREEMENT: 'Saya setuju dengan syarat dan ketentuan',
  ONLINE_TOP_UP_NOW: 'Setor online sekarang',
  DEPOSIT_WITH_RECEIPT: 'SIMPANAN DENGAN PENERIMAAN',
  DEPOSIT_AMOUNT: 'Silakan Masukkan Jumlah Setoran',
  DEPSOSIT_BONUS: 'Bonus setoran klaim',
  TRANSFER_IN: 'pindah Masuk',
  TRANSFER_OUT: 'pindah Keluar',
  TYPE_TRANS: 'Pilih Jenis Transaksi',
  SUBMIT: 'MENYERAHKAN',

  LOADING: 'memuat',
  FROM: 'Dari Tanggal',
  TO: 'Ke Tanggal',
  TRANS_SUC: 'pindah Berhasil',
  TRANS_ERR: 'Kesalahan pindah',
  TRANS_DONE: 'pindah berhasil diselesaikan',
  GOT_IT: 'Mengerti',
  SELECT_GAME: 'Pilih Game',
  CLAIM_LOYALTY_BONUS: 'Klaim bonus loyalitas',
  DEPO_SUC: 'Setor Berhasil',
  DEPO_ERR: 'Kesalahan Setoran',
  DEPO_DONE: 'Permintaan Anda berhasil dikirim',
  SIMPANAN: 'Setoran',
  FILE: 'mengajukan',
  WITH_SUC: 'Menarik Berhasil',
  WITH_ERR: 'Penarikan Kesalahan',
  WITH_DONE: 'Permintaan Anda berhasil dikirim',
  CLICK_DOWNLOAD: 'Klik untuk Mengunduh',
  ENTER_MOBILE: 'Masukkan Nomor Ponsel',
  ENTER_PASS: 'Masukkan Kata Sandi',
  SIGN_IN: 'Masuk',
  DAFTAR: 'Daftar',
  ENTER_DISPLAY_NAME: 'Masukkan Nama Tampilan Anda',
  ENTER_EMAIL: 'Masukkan Email Utama Anda',
  ENTER_AGENT: 'Masukkan email Agen Anda (opsional)',
  RETYPE_PASS: 'Ketik Ulang Kata Sandi Anda',
  BACK_TO_LOGIN: 'KEMBALI UNTUK MASUK',
  DEPOSIT_TO_US:'SETORAN',
  CURRENT_BALANCE: 'CURRENT BALANCE'
}